name: ie-bank-frontend

# Workflow triggers based on branch or pull request
on:
  push:
    branches-ignore: # Trigger on push to any branch except 'main'
      - main
  pull_request:
    branches:
      - main  # Trigger on pull request to 'main' branch

env:
  FRONTEND_WEBAPP_DEV: evaks-fe-dev
  FRONTEND_WEBAPP_UAT: evaks-fe-uat

jobs:
  # Job for building and deploying to Development environment
  build-dev:
    if: github.event_name == 'push'  # Only run for 'push' events
    runs-on: ubuntu-latest
    name: Build and Deploy to Development

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test for development
        run: |
          npm install
          npm run build -- --mode development --dest dist-dev

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app-dev
          path: dist-dev/

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app-dev

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App (Development)'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: .

  # Job for building and deploying to UAT environment
  build-uat:
    if: github.event_name == 'pull_request'  # Only run for 'pull_request' events
    runs-on: ubuntu-latest
    name: Build and Deploy to UAT

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test for UAT
        run: |
          npm install
          npm run build -- --mode uat --dest dist-uat

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app-uat
          path: dist-uat/

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app-uat

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App (UAT)'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_UAT }}
          package: .
